language: ruby
rvm:
  - 2.1.4
  - 2.0.0
  - 1.9.3
env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite
before_script:
  - cp spec/support/database.travis.yml spec/support/database.yml
  - mysql -e 'create database double_entry_test;'
  - psql -c 'create database double_entry_test;' -U postgres
script:
  - rake spec
  - ruby script/jack_hammer -t 2000
gemfile:
  - spec/support/gemfiles/Gemfile.rails-3.2.x
  - spec/support/gemfiles/Gemfile.rails-4.0.x
  - spec/support/gemfiles/Gemfile.rails-4.1.x
